[[Account-API]]
== Account API

=== 회원가입 API

==== 성공

operation::register-success[snippets='http-request,http-response,request-fields,response-fields']

=== 계정 해지 API

==== 성공

operation::cancel-account-success[snippets='http-request,http-response,request-fields,response-fields']

=== 로그인 API

==== 성공

operation::login-success[snippets='http-request,http-response,request-fields,response-fields']

=== 로그아웃 API

==== 성공

operation::logout-success[snippets='http-request,http-response,request-fields,response-fields']

=== Access Token 재발급 API

==== 성공

operation::refresh-success[snippets='http-request,http-response,request-fields,response-fields']

==== 실패

operation::check-email-duplicate-failed[snippets='http-request,http-response,query-parameters,response-fields']

=== 아이디 중복확인 API

==== 성공

operation::check-username-duplicate-success[snippets='http-request,http-response,query-parameters,response-fields']

=== 비밀번호 일치 확인 API

==== 성공

operation::check-username-duplicate-success[snippets='http-request,http-response,query-parameters,response-fields']

==== 실패

operation::check-username-duplicate-success-failed[snippets='http-request,http-response']

=== 아이디 전송 API

==== 성공

operation::find-username-success[snippets='http-request,http-response,request-fields,response-fields']

=== 비밀번호 찾기 OTP 전송 API

==== 성공

operation::send-forgot-password-otp-success[snippets='http-request,http-response,request-fields,response-fields']

=== 비밀번호 재설정 API

==== 성공

operation::set-new-password-success[snippets='http-request,http-response,request-fields,response-fields']

=== 닉네임 변경 API

==== 성공

operation::update-nickname-success[snippets='http-request,http-response,request-fields,response-fields']

== Email API

=== 이메일 중복확인 API

==== 성공

operation::check-email-duplicate-success[snippets='http-request,http-response,query-parameters,response-fields']

==== 실패

operation::check-email-duplicate-failed[snippets='http-request,http-response,query-parameters,response-fields']

=== 이메일 인증여부 확인 API

==== 성공

operation::check-email-verified-success[snippets='http-request,http-response,response-fields']

=== 이메일 등록 API

==== 성공

operation::register-email-success[snippets='http-request,http-response,request-fields,response-fields']

=== 이메일 인증번호 발송 API

==== 성공

operation::verify-email-success[snippets='http-request,http-response,response-fields']

=== 이메일 변경 API

==== 성공

operation::change-email-success[snippets='http-request,http-response,request-fields,response-fields']

=== 이메일 해제 API

==== 성공

operation::unlink-email-success[snippets='http-request,http-response,response-fields']

== Artist API

=== 아티스트 스크롤 조회 API

==== 성공

operation::scroll-artist-success[snippets='http-request,http-response,query-parameters,response-fields']
