[[Account-API]]
== Account API

=== 회원가입 API

==== 성공

operation::register-success[snippets='http-request,http-response,request-fields,response-fields']

=== 로그인 API

==== 성공

operation::login-success[snippets='http-request,http-response,request-fields,response-fields']

=== 구글 소셜 로그인 페이지 진입 API

==== 성공

operation::oauth2-authorization-google-success[snippets='http-request,http-response']

=== 애플 소셜 로그인 페이지 진입 API

==== 성공

operation::oauth2-authorization-apple-success[snippets='http-request,http-response']

=== 로그아웃 API

==== 성공

operation::logout-success[snippets='http-request,http-response,request-fields,response-fields']

=== Access Token 재발급 API

==== 성공

operation::refresh-success[snippets='http-request,http-response,request-fields,response-fields']

=== 이메일 중복확인 API

==== 성공

operation::check-email-duplicate-success[snippets='http-request,http-response,query-parameters,response-fields']

==== 실패

operation::check-email-duplicate-failed[snippets='http-request,http-response,query-parameters,response-fields']

=== 아이디 중복확인 API

==== 성공

operation::check-username-duplicate-success[snippets='http-request,http-response,query-parameters,response-fields']

==== 실패

operation::check-username-duplicate-success-failed[snippets='http-request,http-response']

=== 이메일 인증여부 확인 API

==== 성공

operation::check-email-verified-success[snippets='http-request,http-response,response-fields']

=== 비밀번호 찾기 OTP 전송 API

==== 성공

operation::send-forgot-password-otp-success[snippets='http-request,http-response,request-fields,response-fields']

=== 비밀번호 재설정 API

==== 성공

operation::set-new-password-success[snippets='http-request,http-response,request-fields,response-fields']

=== 닉네임 변경 API

==== 성공

operation::update-nickname-success[snippets='http-request,http-response,request-fields,response-fields']
